create table categories (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table lessons (
    id int8 generated by default as identity,
    date_of_lesson date,
    schedule timestamp,
    status varchar(255),
    mentee_id int8,
    mentor_id int8,
    primary key (id)
 );

create table mentor_info (
    id int8 generated by default as identity,
    certificates varchar(255),
    description varchar(255),
    education varchar(255),
    price numeric(19, 2),
    rating numeric(19, 2),
    speciality varchar(255),
    work_experience varchar(255),
    category varchar(255),
    user_id int8,
    primary key (id)
 );

create table mentor_tags (
    mentor_id int8 not null,
    tag_id int8 not null,
    tag varchar(255) not null,
    primary key (mentor_id, tag_id, tag)
);

create table roles (
    role varchar(255) not null,
    primary key (role)
);

create table tags (
    id int8 generated by default as identity,
    name varchar(255),
    category varchar(255),
    primary key (id)
);

create table user_interests (
    user_id int8 not null,
    tag_id int8 not null,
    tag_name varchar(255) not null,
    primary key (user_id, tag_id, tag_name)
);

create table user_roles (
    user_id int8 not null,
    role varchar(255) not null,
    primary key (user_id, role)
);

create table users (
    id int8 generated by default as identity,
    balance numeric(19, 2),
    birthdate date,
    created_at date,
    description varchar(255),
    email varchar(255),
    is_active boolean,
    password varchar(255),
    phone_number varchar(255),
    speciality varchar(255),
    time_zone numeric(19, 2),
    user_picture varchar(255),
    username varchar(255),
    primary key (id)
);

alter table if exists categories
    add constraint unique_category_name_constraint unique (name);

alter table if exists tags
    add constraint unique_tag_id_and_name_constraint unique (id, name);

alter table if exists users
    add constraint unique_user_email_and_phonenumber_constraint unique (email, phone_number);

alter table if exists lessons
    add constraint mentee_id_fk_for_lesson_constraint foreign key (mentee_id) references users;

alter table if exists lessons
    add constraint mentor_id_fk_for_lesson_constraint foreign key (mentor_id) references mentor_info;

alter table if exists mentor_info
    add constraint category_name_fk_for_mentor_constraint foreign key (category) references categories (name);

alter table if exists mentor_info
    add constraint user_id_fk_for_mentor_constraint foreign key (user_id) references users;

alter table if exists mentor_tags
    add constraint mentor_id_fk_for_mentor_tags_constraint foreign key (mentor_id) references mentor_info;

alter table if exists tags
    add constraint category_name_fk_for_tags_constraint foreign key (category) references categories (name);

alter table if exists user_interests
    add constraint user_id_fk_for_user_interests_constraint foreign key (user_id) references users;

alter table if exists user_roles
    add constraint role_fk_for_user_roles_constraint foreign key (role) references roles